### ISSUE TITLE
How to extract images from '/System/Library/Fonts/Apple Color Emoji.ttc'?

### ISSUE THREAD

**Issue by NightMachinary** [kreativekorp/bitsnpicas#13]
How to extract images from '/System/Library/Fonts/Apple Color Emoji.ttc'? I also tried using it on https://github.com/samuelngs/apple-emoji-linux/releases/download/latest/AppleColorEmoji.ttf , but it said:
```
❯ java -jar ~/bin/BitsNPicas.jar extractsbix AppleColorEmoji.ttf
Processing /Users/evar/TMP/AppleColorEmoji.ttf... no sbix table found.
```

**Comment by RebeccaRGB** [comment]
For a TTC file, you need to split it into its constituent TTFs. I have
tools in other repositories that can do that:

https://github.com/kreativekorp/pushchar:
java com.kreative.pushchar.test.TtcUnpack AppleColorEmoji.ttc

https://github.com/kreativekorp/charset:
python bin/ttc-unpack.py AppleColorEmoji.ttc

For the version in the apple-emoji-linux repository, that uses a different
format, so instead of extractsbix you need to use extractcbdt:
java -jar ~/bin/BitsNPicas.jar extractcbdt AppleColorEmoji.ttf
