### ISSUE TITLE
Any roadmaps for v2?

### ISSUE THREAD

**Issue by diaowinner** [kreativekorp/bitsnpicas#27]
I saw some issues are labeled with "fixed in v2". so what are the roadmaps for v2? Is the software still open-sourced?

**Comment by RebeccaRGB** [comment]
Yes, it's still open source. You can check out the repository right now and build it and those issues will be fixed. It's just a marker that it's fixed in the repo but not in the current release. When the release is made those issues will be closed. Current ETA is September when Unicode 15.0 is released.

**Comment by diaowinner** [comment]
Thanks.
